# Generated by Django 3.2 on 2021-04-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classAPIview', '0001_initial'),
        ('functionAPIview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classAPIview.department'),
        ),
    ]
