# Generated by Django 3.2 on 2021-04-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classAPIview', '0001_initial'),
        ('functionAPIview', '0002_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='classAPIview.department'),
        ),
    ]
